// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.disertatie.mylibrary.domain;

import com.disertatie.mylibrary.domain.Author;
        import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Author_Roo_Configurable {

    declare @type: Author: @Configurable;

}
